### ISSUE TITLE
Questions on adding headers to nextWithApollo

### ISSUE THREAD

**Issue by p-null** [TomDoesTech/NextJS-With-Apollo-Client_Tutorial#1]
Hi Tom,
Thanks for sharing Nextjs + Apollo tutorials! I really like your videos.

As I was following this repo to test sending graphql query with headers, I found that no headers are added to the graphql request even when I hard-coded my header into `nextWithApollo`.

Would you mind taking a look at my example? It's a fork of this repo with just a few lines of modification. I also watched your latest video on Authentication and checked the github repo you linked but I still couldn't figure out what's wrong with my example.

Here is the fork: https://github.com/p-null/NextJS-With-Apollo-Client-Tutorial

**What I did and why**
I found my request to my graphql api always failed due to not including authorization header even though I added them to `nextWithApollo`.
I removed the `getDataFromTree` when calling `WithApollo` so that I can see the network requests in brwoswer(Otherwise I don't know what the headers are).
Then I found there is no custom headers in the request header even when I hardcoded the header `"my-header": "blah"`.

Appreciate your help!

**Comment by tomanagle** [comment]
Sorry @p-null , just saw this. I have cloned your repo and I'll take a look

**Comment by tomanagle** [comment]
@p-null I created a PR on your repo: https://github.com/p-null/NextJS-With-Apollo-Client-Tutorial/pull/1

The solution was to move the headers to the HttpLink, so the client looks like this:

```
const withApollo = nextWithApollo(
  ({ initialState, headers }) => {
    return new ApolloClient({
      ssrMode: typeof window === "undefined",
      link: new HttpLink({
        uri: "http://localhost:8080/graphql",
        headers: {
          ...(headers as Record<string, string>),
          authorization: "hnfndkjfnjsd",
          "my-header": "blah",
        },
      }),

      cache: new InMemoryCache().restore(initialState || {}),
    });
  },
  {
    render: ({ Page, props }) => {
      const router = useRouter();
      return (
        <ApolloProvider client={props.apollo}>
          <Page {...props} {...router} />
        </ApolloProvider>
      );
    },
  }
);

export default withApollo;
```

**Comment by p-null** [comment]
Thanks so much, Tom. I successfully connected to my graphql server with the change you proposed. 👍 

Keep up the good work. Love your youtube channel! ❤️
